const pages=Array.from({length:7},(_,i)=>`assets/page-${i+1}.jpg`);let pageIndex=0;const $=s=>document.querySelector(s);
const params=new URLSearchParams(location.search);const guest=params.get('to')||params.get('guest');if(guest)$('#recipient').textContent=guest.trim().slice(0,80);
const audio=$('#bgm');let started=false;
async function enter(){if(started)return;started=true;$('#seal').classList.add('opened');$('#welcome .opening-card').classList.add('open');try{await audio.play()}catch(e){}setTimeout(()=>$('#welcome').classList.add('hide'),850);$('#nav').style.opacity='1'}
$('#seal').addEventListener('click',enter);$('#openInvite').addEventListener('click',enter);$('#welcome .opening-card').addEventListener('click',enter);
$('#music').addEventListener('click',async()=>{if(audio.paused){try{await audio.play()}catch(e){}}else audio.pause()});
const target=new Date('2026-11-26T12:14:00+05:30').getTime();function countdown(){let d=Math.max(0,target-Date.now());const vals={days:Math.floor(d/86400000)};d%=86400000;vals.hours=Math.floor(d/3600000);d%=3600000;vals.minutes=Math.floor(d/60000);d%=60000;vals.seconds=Math.floor(d/1000);for(const [k,v] of Object.entries(vals))$(`[data-unit="${k}"]`).textContent=String(v).padStart(2,'0')}countdown();setInterval(countdown,1000);
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));
function render(){const src=pages[pageIndex];$('#invitePage').src=src;$('#lightImage').src=src;$('#invitePage').alt=`Wedding invitation page ${pageIndex+1}`;$('#pageNumber').textContent=String(pageIndex+1).padStart(2,'0');$('#progressBar').style.width=`${((pageIndex+1)/pages.length)*100}%`}
function move(n){pageIndex=(pageIndex+n+pages.length)%pages.length;render()}$('#prev').onclick=()=>move(-1);$('#next').onclick=()=>move(1);$('#pageOpen').onclick=()=>{$('#lightbox').hidden=false;document.body.style.overflow='hidden'};$('#close').onclick=close;$('#lightPrev').onclick=()=>move(-1);$('#lightNext').onclick=()=>move(1);$('#lightbox').onclick=e=>{if(e.target.id==='lightbox')close()};function close(){$('#lightbox').hidden=true;document.body.style.overflow=''}let sx=0;$('#pageOpen').addEventListener('touchstart',e=>sx=e.changedTouches[0].clientX,{passive:true});$('#pageOpen').addEventListener('touchend',e=>{let dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)move(dx<0?1:-1)},{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});render();
